### ISSUE TITLE
LUA error in combination with Bufflehead

### ISSUE THREAD

**Issue by Breakerzeus** [Sheday/wowaudit-invite-tool#4]
Hi, could this LUA error an issue with the wowaudit-invite-tool addon or is it something with the addon "Bufflehead"?

> 1x [ADDON_ACTION_BLOCKED] AddOn 'WowauditInviteTool' tried to call the protected function 'BuffleheadSecureHeaderPlayerBuffsAuraButton10:SetFrameLevel()'.
> [string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
> [string "=[C]"]: in function `SetFrameLevel'
> [string "@WowauditInviteTool\libs\LibStrataFix\LibStrataFix-10034.lua"]:71: in function <...owauditInviteTool\libs\LibStrataFix\LibStrataFix.lua:58>
> [string "@WowauditInviteTool\libs\LibStrataFix\LibStrataFix-10034.lua"]:81: in function <...owauditInviteTool\libs\LibStrataFix\LibStrataFix.lua:76>
> [string "@WowauditInviteTool\libs\LibStrataFix\LibStrataFix-10034.lua"]:141: in function <...owauditInviteTool\libs\LibStrataFix\LibStrataFix.lua:121>
> [string "=(tail call)"]: ?
> [string "=[C]"]: ?
> [string "=[C]"]: in function `CreateFrame'
> [string "@FrameXML\SecureGroupHeaders.lua"]:725: in function <FrameXML\SecureGroupHeaders.lua:724>
> [string "@FrameXML\SecureGroupHeaders.lua"]:762: in function <FrameXML\SecureGroupHeaders.lua:735>
> [string "@FrameXML\SecureGroupHeaders.lua"]:1073: in function `SecureAuraHeader_Update'
> [string "@FrameXML\SecureGroupHeaders.lua"]:693: in function <FrameXML\SecureGroupHeaders.lua:689>

**Comment by emielvanlankveld** [comment]
LibStrata is responsible for the basic layout of the window, which is pretty standard. I suspect Bufflehead perhaps adds some logic to this process and an error is thrown there? I wouldn't know how it'd be related to this addon at least.

**Comment by Breakerzeus** [comment]
I'm wondering since this only occures when wowaudit addon is active. But yeah, if it's a general incompability with bufflehead then I just have to deal with it I guess.

**Comment by emielvanlankveld** [comment]
It also only happens when the Bufflehead addon is active, I assume? So the combination is the problem?

**Comment by Breakerzeus** [comment]
yeah that's the case. Only one of them works fine. As soon as both are active and I get into combat, LUA Error appears.

**Comment by Sheday** [comment]
This should now be resolved by https://github.com/wowaudit/invite-tool/issues/8
